
  name: nomacs
  version: 3.11.0
  summary: nomacs is a free, open source image viewer.
  description: |
    You can use it for viewing all common image formats 
    including RAW and psd images. nomacs is licensed 
    under the GNU General Public License v3 and 
    available for Windows, Linux, FreeBSD, Mac, and OS/2.
  icon: ./ImageLounge/nomacs.svg

  # grade: devel # must be 'stable' to release into candidate/stable channels
  # confinement: devmode # use 'strict' once you have the right plugs and slots
  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: strict # use 'strict' once you have the right plugs and slots

  apps:
    nomacs:
      command: desktop-launch nomacs
      desktop: ./../ImageLounge/nomacs.desktop
      plugs: [home, network, x11]

  parts:

    # add quazip
    quazip:
      source: https://github.com/stachenov/quazip.git
      plugin: cmake
      configflags: 
        - -DCMAKE_BUILD_TYPE=Release
    
    # add all official plugins
    nomacs-plugins:
      source: https://github.com/nomacs/nomacs-plugins.git
      plugin: dump

    # install themes
    nomacs-resources:
      source: ./ImageLounge/src/themes
      plugin: dump
      organize:
        '*.css': /bin/themes/
        
    # compile nomacs
    nomacs:
      plugin: cmake
      source: ./ImageLounge
      configflags: 
        - -DCMAKE_BUILD_TYPE=Release
        - -DENABLE_QUAZIP=ON
        - -DUSE_SYSTEM_QUAZIP=ON
        - -DENABLE_TRANSLATIONS=ON
      stage-packages:
        - libc6
        - libraw-dev
        - libtbb-dev
        - libjasper-dev
        - libexiv2-dev
        - libqt5printsupport5
        - libqt5concurrent5
        - libquazip-dev
        # the mistirious rest...
        - libatk-adaptor 
        - libgail-common
        - libqt5gui5
        - libqt5svg5 # for loading icon themes which are svg
        - qt5-image-formats-plugins
        - libcanberra-gtk-module
        # - libxkbcommon0
        # - ttf-ubuntu-font-family
        # - dmz-cursor-theme
        # - light-themes
        # - adwaita-icon-theme
        # - gnome-themes-standard
        # - shared-mime-info
        # - libgdk-pixbuf2.0-0
        # - appmenu-qt5
        # - locales-all
      build-packages:
        - debhelper
        - cdbs
        - qt5-qmake
        - qttools5-dev-tools
        - qt5-default
        - qttools5-dev
        - libqt5svg5-dev
        - qt5-image-formats-plugins
        - libexiv2-dev
        - libraw-dev
        - libopencv-dev
        - cmake
        - libtiff-dev
        - libquazip-dev
        - libwebp-dev
        - git
        - g++
        - libzip-dev
      after: 
        - desktop-qt5
        - nomacs-plugins
        - quazip

